// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// USER AUTH / REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERR = "AUTH_ERR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";


export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_FAILED ="RESET_PASSWORD_FAILED"
// USER PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
// PRODUCTS
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
// EVENTS
export const ADD_EVENT = "ADD_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENT = "GET_EVENT";
export const EVENT_ERROR = "EVENT_ERROR";
export const DELETE_EVENT = "DELETE_EVENT";
// POSTS AND COMMENT
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const UPDATE_LIKES_ERROR = "UPDATE_LIKES_ERROR";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
// SPECIFIC USER'S POST
export const GET_USERS_POSTS = "GET_USERS_POSTS";

// LIST OF UNIVERSITIES
export const GET_UNIVERSITY = "GET_UNIVERSITY";
export const ERR_GET_UNIVERSITY = "ERR_GET_UNIVERSITY";

//FOllow and UNFOLLOW
export const FOLLOW_USER = "FOLLOW_USER"
export const UNFOLLOW_USER = "UNFOLOW_USER"
export const ERR_FOLLOW = "ERR_FOLLOW"

